#!/bin/bash

set -e

#proxy='--proxy=localhost:3128'

function install_deps {
	pip $proxy install -e .
	hash -r
	cp development.ini{_tmpl,}
	cp test.ini{_tmpl,}
}

function make_env {
	env_name=$1
	virtualenv --no-site-packages $env_name
}

function use_env {
	env_name=$1
	cd $env_name
	. bin/activate
	mkdir -p src
	cd src
}

function setup_repo {
	repo=$1
	git clone ssh://git@github.com/okfn/${repo}.git
	( cd $repo ; install_deps )
}

env_name=$1
make_env $env_name
use_env $env_name

setup_repo openspending
setup_repo openspending.etl

( cd openspending.etl ; ln -s .packageroot/openspending.etl.egg-info . )
