#!/bin/bash
set -eu

export DIR=$1
mkdir $DIR && cd $DIR

virtualenv --no-site-packages pyenv
set +u ; . pyenv/bin/activate ; set -u

pip install pylons
pip install psycopg2
pip install genshi
pip install webob==1.0.8
pip install PasteScript==1.7.4.2
pip install -e git+http://github.com/okfn/openspending#egg=openspending
pip install -e git+http://github.com/okfn/openspending.etl#egg=openspending.etl
pip install -e git+http://github.com/okfn/openspending.plugins.treemap#egg=openspending.plugins.treemap
pip install -e git+http://github.com/okfn/openspending.plugins.datatables#egg=openspending.plugins.datatables
pip install -r pip-sources.txt 
