#!/bin/bash

# Example of how to install OpenSpending programmatically on Ubuntu

# N.B. pip does not install dependencies of packages installed with -e
# Therefore we have to enumerate some of them specifically for the time being

set -eu

export DIR=$1
mkdir $DIR && cd $DIR

virtualenv --no-site-packages pyenv
set +u ; . pyenv/bin/activate ; set -u

pip install psycopg2
pip install translationstring
pip install -e git+http://github.com/openspending/osvalidate#egg=osvalidate
pip install -e git+http://github.com/openspending/openspending#egg=openspending