# -*- coding: utf-8 -*-
# http://www.currency-iso.org/iso_index/iso_tables/iso_tables_a1.htm
CURRENCIES = [
    {'name': u'Afghani',
     'symbol': 'AFN',
     'numeric': 971},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Lek',
     'symbol': 'ALL',
     'numeric': 8},
    {'name': u'Algerian Dinar',
     'symbol': 'DZD',
     'numeric': 12},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Kwanza',
     'symbol': 'AOA',
     'numeric': 973},
    {'name': u'East Caribbean Dollar',
     'symbol': 'XCD',
     'numeric': 951},
    {'name': u'East Caribbean Dollar',
     'symbol': 'XCD',
     'numeric': 951},
    {'name': u'Argentine Peso',
     'symbol': 'ARS',
     'numeric': 32},
    {'name': u'Armenian Dram',
     'symbol': 'AMD',
     'numeric': 51},
    {'name': u'Aruban Guilder',
     'symbol': 'AWG',
     'numeric': 533},
    {'name': u'Australian Dollar',
     'symbol': 'AUD',
     'numeric': 36},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Azerbaijanian Manat',
     'symbol': 'AZN',
     'numeric': 944},
    {'name': u'Bahamian Dollar',
     'symbol': 'BSD',
     'numeric': 44},
    {'name': u'Bahraini Dinar',
     'symbol': 'BHD',
     'numeric': 48},
    {'name': u'Taka',
     'symbol': 'BDT',
     'numeric': 50},
    {'name': u'Barbados Dollar',
     'symbol': 'BBD',
     'numeric': 52},
    {'name': u'Belarussian Ruble',
     'symbol': 'BYR',
     'numeric': 974},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Belize Dollar',
     'symbol': 'BZD',
     'numeric': 84},
    {'name': u'CFA Franc BCEAO ',
     'symbol': 'XOF',
     'numeric': 952},
    {'name': u'Bermudian Dollar',
     'symbol': 'BMD',
     'numeric': 60},
    {'name': u'Indian Rupee',
     'symbol': 'INR',
     'numeric': 356},
    {'name': u'Ngultrum ',
     'symbol': 'BTN',
     'numeric': 64},
    {'name': u'Boliviano',
     'symbol': 'BOB',
     'numeric': 68},
    {'name': u'Mvdol ',
     'symbol': 'BOV',
     'numeric': 984},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'Convertible Mark',
     'symbol': 'BAM',
     'numeric': 977},
    {'name': u'Pula',
     'symbol': 'BWP',
     'numeric': 72},
    {'name': u'Norwegian Krone',
     'symbol': 'NOK',
     'numeric': 578},
    {'name': u'Brazilian Real',
     'symbol': 'BRL',
     'numeric': 986},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'Brunei Dollar',
     'symbol': 'BND',
     'numeric': 96},
    {'name': u'Bulgarian Lev',
     'symbol': 'BGN',
     'numeric': 975},
    {'name': u'CFA Franc BCEAO ',
     'symbol': 'XOF',
     'numeric': 952},
    {'name': u'Burundi Franc',
     'symbol': 'BIF',
     'numeric': 108},
    {'name': u'Riel',
     'symbol': 'KHR',
     'numeric': 116},
    {'name': u'CFA Franc BEAC ',
     'symbol': 'XAF',
     'numeric': 950},
    {'name': u'Canadian Dollar',
     'symbol': 'CAD',
     'numeric': 124},
    {'name': u'Cape Verde Escudo',
     'symbol': 'CVE',
     'numeric': 132},
    {'name': u'Cayman Islands Dollar',
     'symbol': 'KYD',
     'numeric': 136},
    {'name': u'CFA Franc BEAC ',
     'symbol': 'XAF',
     'numeric': 950},
    {'name': u'CFA Franc BEAC ',
     'symbol': 'XAF',
     'numeric': 950},
    {'name': u'Chilean Peso',
     'symbol': 'CLP',
     'numeric': 152},
    {'name': u'Unidades de fomento ',
     'symbol': 'CLF',
     'numeric': 990},
    {'name': u'Yuan Renminbi',
     'symbol': 'CNY',
     'numeric': 156},
    {'name': u'Australian Dollar',
     'symbol': 'AUD',
     'numeric': 36},
    {'name': u'Australian Dollar',
     'symbol': 'AUD',
     'numeric': 36},
    {'name': u'Colombian Peso',
     'symbol': 'COP',
     'numeric': 170},
    {'name': u'Unidad de Valor Real ',
     'symbol': 'COU',
     'numeric': 970},
    {'name': u'Comoro Franc',
     'symbol': 'KMF',
     'numeric': 174},
    {'name': u'CFA Franc BEAC ',
     'symbol': 'XAF',
     'numeric': 950},
    {'name': u'Congolese Franc ',
     'symbol': 'CDF',
     'numeric': 976},
    {'name': u'New Zealand Dollar',
     'symbol': 'NZD',
     'numeric': 554},
    {'name': u'Costa Rican Colon',
     'symbol': 'CRC',
     'numeric': 188},
    {'name': u'CFA Franc BCEAO ',
     'symbol': 'XOF',
     'numeric': 952},
    {'name': u'Croatian Kuna',
     'symbol': 'HRK',
     'numeric': 191},
    {'name': u'Cuban Peso',
     'symbol': 'CUP',
     'numeric': 192},
    {'name': u'Peso Convertible  ',
     'symbol': 'CUC',
     'numeric': 931},
    {'name': u'Netherlands Antillean Guilder',
     'symbol': 'ANG',
     'numeric': 532},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Czech Koruna',
     'symbol': 'CZK',
     'numeric': 203},
    {'name': u'Danish Krone',
     'symbol': 'DKK',
     'numeric': 208},
    {'name': u'Djibouti Franc',
     'symbol': 'DJF',
     'numeric': 262},
    {'name': u'East Caribbean Dollar',
     'symbol': 'XCD',
     'numeric': 951},
    {'name': u'Dominican Peso',
     'symbol': 'DOP',
     'numeric': 214},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'Egyptian Pound',
     'symbol': 'EGP',
     'numeric': 818},
    {'name': u'El Salvador Colon',
     'symbol': 'SVC',
     'numeric': 222},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'CFA Franc BEAC ',
     'symbol': 'XAF',
     'numeric': 950},
    {'name': u'Nakfa',
     'symbol': 'ERN',
     'numeric': 232},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Ethiopian Birr',
     'symbol': 'ETB',
     'numeric': 230},
    {'name': u'Euro ',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Falkland Islands Pound',
     'symbol': 'FKP',
     'numeric': 238},
    {'name': u'Danish Krone',
     'symbol': 'DKK',
     'numeric': 208},
    {'name': u'Fiji Dollar',
     'symbol': 'FJD',
     'numeric': 242},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'CFP Franc',
     'symbol': 'XPF',
     'numeric': 953},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'CFA Franc BEAC ',
     'symbol': 'XAF',
     'numeric': 950},
    {'name': u'Dalasi',
     'symbol': 'GMD',
     'numeric': 270},
    {'name': u'Lari',
     'symbol': 'GEL',
     'numeric': 981},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Cedi',
     'symbol': 'GHS',
     'numeric': 936},
    {'name': u'Gibraltar Pound',
     'symbol': 'GIP',
     'numeric': 292},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Danish Krone',
     'symbol': 'DKK',
     'numeric': 208},
    {'name': u'East Caribbean Dollar',
     'symbol': 'XCD',
     'numeric': 951},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'Quetzal',
     'symbol': 'GTQ',
     'numeric': 320},
    {'name': u'Pound Sterling',
     'symbol': 'GBP',
     'numeric': 826},
    {'name': u'Guinea Franc',
     'symbol': 'GNF',
     'numeric': 324},
    {'name': u'CFA Franc BCEAO ',
     'symbol': 'XOF',
     'numeric': 952},
    {'name': u'Guyana Dollar',
     'symbol': 'GYD',
     'numeric': 328},
    {'name': u'Gourde',
     'symbol': 'HTG',
     'numeric': 332},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'Australian Dollar',
     'symbol': 'AUD',
     'numeric': 36},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Lempira',
     'symbol': 'HNL',
     'numeric': 340},
    {'name': u'Hong Kong Dollar',
     'symbol': 'HKD',
     'numeric': 344},
    {'name': u'Forint',
     'symbol': 'HUF',
     'numeric': 348},
    {'name': u'Iceland Krona',
     'symbol': 'ISK',
     'numeric': 352},
    {'name': u'Indian Rupee',
     'symbol': 'INR',
     'numeric': 356},
    {'name': u'Rupiah',
     'symbol': 'IDR',
     'numeric': 360},
    {'name': u'SDR (Special Drawing Right)',
     'symbol': 'XDR',
     'numeric': 960},
    {'name': u'Iranian Rial',
     'symbol': 'IRR',
     'numeric': 364},
    {'name': u'Iraqi Dinar',
     'symbol': 'IQD',
     'numeric': 368},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Pound Sterling',
     'symbol': 'GBP',
     'numeric': 826},
    {'name': u'New Israeli Sheqel',
     'symbol': 'ILS',
     'numeric': 376},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Jamaican Dollar',
     'symbol': 'JMD',
     'numeric': 388},
    {'name': u'Yen',
     'symbol': 'JPY',
     'numeric': 392},
    {'name': u'Pound Sterling',
     'symbol': 'GBP',
     'numeric': 826},
    {'name': u'Jordanian Dinar',
     'symbol': 'JOD',
     'numeric': 400},
    {'name': u'Tenge',
     'symbol': 'KZT',
     'numeric': 398},
    {'name': u'Kenyan Shilling',
     'symbol': 'KES',
     'numeric': 404},
    {'name': u'Australian Dollar',
     'symbol': 'AUD',
     'numeric': 36},
    {'name': u'North Korean Won',
     'symbol': 'KPW',
     'numeric': 408},
    {'name': u'Won',
     'symbol': 'KRW',
     'numeric': 410},
    {'name': u'Kuwaiti Dinar',
     'symbol': 'KWD',
     'numeric': 414},
    {'name': u'Som',
     'symbol': 'KGS',
     'numeric': 417},
    {'name': u'Kip',
     'symbol': 'LAK',
     'numeric': 418},
    {'name': u'Latvian Lats',
     'symbol': 'LVL',
     'numeric': 428},
    {'name': u'Lebanese Pound',
     'symbol': 'LBP',
     'numeric': 422},
    {'name': u'Loti',
     'symbol': 'LSL',
     'numeric': 426},
    {'name': u'Rand',
     'symbol': 'ZAR',
     'numeric': 710},
    {'name': u'Liberian Dollar',
     'symbol': 'LRD',
     'numeric': 430},
    {'name': u'Libyan Dinar',
     'symbol': 'LYD',
     'numeric': 434},
    {'name': u'Swiss Franc',
     'symbol': 'CHF',
     'numeric': 756},
    {'name': u'Lithuanian Litas',
     'symbol': 'LTL',
     'numeric': 440},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Pataca',
     'symbol': 'MOP',
     'numeric': 446},
    {'name': u'Denar',
     'symbol': 'MKD',
     'numeric': 807},
    {'name': u'Malagasy Ariary',
     'symbol': 'MGA',
     'numeric': 969},
    {'name': u'Kwacha',
     'symbol': 'MWK',
     'numeric': 454},
    {'name': u'Malaysian Ringgit',
     'symbol': 'MYR',
     'numeric': 458},
    {'name': u'Rufiyaa',
     'symbol': 'MVR',
     'numeric': 462},
    {'name': u'CFA Franc BCEAO ',
     'symbol': 'XOF',
     'numeric': 952},
    {'name': u'Euro ',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Ouguiya',
     'symbol': 'MRO',
     'numeric': 478},
    {'name': u'Mauritius Rupee',
     'symbol': 'MUR',
     'numeric': 480},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'ADB Unit of Account',
     'symbol': 'XUA',
     'numeric': 965},
    {'name': u'Mexican Peso',
     'symbol': 'MXN',
     'numeric': 484},
    {'name': u'Mexican Unidad de Inversion (UDI) ',
     'symbol': 'MXV',
     'numeric': 979},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'Moldovan Leu',
     'symbol': 'MDL',
     'numeric': 498},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Tugrik',
     'symbol': 'MNT',
     'numeric': 496},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'East Caribbean Dollar',
     'symbol': 'XCD',
     'numeric': 951},
    {'name': u'Moroccan Dirham',
     'symbol': 'MAD',
     'numeric': 504},
    {'name': u'Metical',
     'symbol': 'MZN',
     'numeric': 943},
    {'name': u'Kyat',
     'symbol': 'MMK',
     'numeric': 104},
    {'name': u'Namibia Dollar',
     'symbol': 'NAD',
     'numeric': 516},
    {'name': u'South African Rand',
     'symbol': 'ZAR',
     'numeric': 710},
    {'name': u'Australian Dollar',
     'symbol': 'AUD',
     'numeric': 36},
    {'name': u'Nepalese Rupee',
     'symbol': 'NPR',
     'numeric': 524},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'CFP Franc',
     'symbol': 'XPF',
     'numeric': 953},
    {'name': u'New Zealand Dollar',
     'symbol': 'NZD',
     'numeric': 554},
    {'name': u'Cordoba Oro',
     'symbol': 'NIO',
     'numeric': 558},
    {'name': u'CFA Franc BCEAO ',
     'symbol': 'XOF',
     'numeric': 952},
    {'name': u'Naira',
     'symbol': 'NGN',
     'numeric': 566},
    {'name': u'New Zealand Dollar',
     'symbol': 'NZD',
     'numeric': 554},
    {'name': u'Australian Dollar',
     'symbol': 'AUD',
     'numeric': 36},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'Norwegian Krone',
     'symbol': 'NOK',
     'numeric': 578},
    {'name': u'Rial Omani',
     'symbol': 'OMR',
     'numeric': 512},
    {'name': u'Pakistan Rupee',
     'symbol': 'PKR',
     'numeric': 586},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'Balboa',
     'symbol': 'PAB',
     'numeric': 590},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'Kina',
     'symbol': 'PGK',
     'numeric': 598},
    {'name': u'Guarani',
     'symbol': 'PYG',
     'numeric': 600},
    {'name': u'Nuevo Sol',
     'symbol': 'PEN',
     'numeric': 604},
    {'name': u'Philippine Peso',
     'symbol': 'PHP',
     'numeric': 608},
    {'name': u'New Zealand Dollar',
     'symbol': 'NZD',
     'numeric': 554},
    {'name': u'Zloty',
     'symbol': 'PLN',
     'numeric': 985},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'Qatari Rial',
     'symbol': 'QAR',
     'numeric': 634},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Leu  ',
     'symbol': 'RON',
     'numeric': 946},
    {'name': u'Russian Ruble',
     'symbol': 'RUB',
     'numeric': 643},
    {'name': u'Rwanda Franc',
     'symbol': 'RWF',
     'numeric': 646},
    {'name': u'Saint Helena Pound',
     'symbol': 'SHP',
     'numeric': 654},
    {'name': u'East Caribbean Dollar',
     'symbol': 'XCD',
     'numeric': 951},
    {'name': u'East Caribbean Dollar',
     'symbol': 'XCD',
     'numeric': 951},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'East Caribbean Dollar',
     'symbol': 'XCD',
     'numeric': 951},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Tala',
     'symbol': 'WST',
     'numeric': 882},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Dobra',
     'symbol': 'STD',
     'numeric': 678},
    {'name': u'Saudi Riyal',
     'symbol': 'SAR',
     'numeric': 682},
    {'name': u'CFA Franc BCEAO ',
     'symbol': 'XOF',
     'numeric': 952},
    {'name': u'Serbian Dinar',
     'symbol': 'RSD',
     'numeric': 941},
    {'name': u'Seychelles Rupee',
     'symbol': 'SCR',
     'numeric': 690},
    {'name': u'Leone',
     'symbol': 'SLL',
     'numeric': 694},
    {'name': u'Singapore Dollar',
     'symbol': 'SGD',
     'numeric': 702},
    {'name': u'Netherlands Antillean Guilder',
     'symbol': 'ANG',
     'numeric': 532},
    {'name': u'Sucre',
     'symbol': 'XSU',
     'numeric': 994},
    {'name': u'Euro ',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Solomon Islands Dollar',
     'symbol': 'SBD',
     'numeric': 90},
    {'name': u'Somali Shilling',
     'symbol': 'SOS',
     'numeric': 706},
    {'name': u'Rand',
     'symbol': 'ZAR',
     'numeric': 710},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Sri Lanka Rupee',
     'symbol': 'LKR',
     'numeric': 144},
    {'name': u'Sudanese Pound ',
     'symbol': 'SDG',
     'numeric': 938},
    {'name': u'Surinam Dollar',
     'symbol': 'SRD',
     'numeric': 968},
    {'name': u'Norwegian Krone',
     'symbol': 'NOK',
     'numeric': 578},
    {'name': u'Lilangeni',
     'symbol': 'SZL',
     'numeric': 748},
    {'name': u'Swedish Krona',
     'symbol': 'SEK',
     'numeric': 752},
    {'name': u'Swiss Franc',
     'symbol': 'CHF',
     'numeric': 756},
    {'name': u'WIR Euro ',
     'symbol': 'CHE',
     'numeric': 947},
    {'name': u'WIR Franc  ',
     'symbol': 'CHW',
     'numeric': 948},
    {'name': u'Syrian Pound',
     'symbol': 'SYP',
     'numeric': 760},
    {'name': u'New Taiwan Dollar',
     'symbol': 'TWD',
     'numeric': 901},
    {'name': u'Somoni      ',
     'symbol': 'TJS',
     'numeric': 972},
    {'name': u'Tanzanian Shilling',
     'symbol': 'TZS',
     'numeric': 834},
    {'name': u'Baht',
     'symbol': 'THB',
     'numeric': 764},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'CFA Franc BCEAO ',
     'symbol': 'XOF',
     'numeric': 952},
    {'name': u'New Zealand Dollar',
     'symbol': 'NZD',
     'numeric': 554},
    {'name': u'Pa’anga',
     'symbol': 'TOP',
     'numeric': 776},
    {'name': u'Trinidad and Tobago Dollar',
     'symbol': 'TTD',
     'numeric': 780},
    {'name': u'Tunisian Dinar',
     'symbol': 'TND',
     'numeric': 788},
    {'name': u'Turkish Lira  ',
     'symbol': 'TRY',
     'numeric': 949},
    {'name': u'New Manat',
     'symbol': 'TMT',
     'numeric': 934},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'Australian Dollar',
     'symbol': 'AUD',
     'numeric': 36},
    {'name': u'Uganda Shilling',
     'symbol': 'UGX',
     'numeric': 800},
    {'name': u'Hryvnia',
     'symbol': 'UAH',
     'numeric': 980},
    {'name': u'UAE Dirham',
     'symbol': 'AED',
     'numeric': 784},
    {'name': u'Pound Sterling',
     'symbol': 'GBP',
     'numeric': 826},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'US Dollar (Next day) ',
     'symbol': 'USN',
     'numeric': 997},
    {'name': u'US Dollar (Same day) ',
     'symbol': 'USS',
     'numeric': 998},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'Peso Uruguayo',
     'symbol': 'UYU',
     'numeric': 858},
    {'name': u'Uruguay Peso en Unidades Indexadas (URUIURUI)  ',
     'symbol': 'UYI',
     'numeric': 940},
    {'name': u'Uzbekistan Sum',
     'symbol': 'UZS',
     'numeric': 860},
    {'name': u'Vatu',
     'symbol': 'VUV',
     'numeric': 548},
    {'name': u'Euro',
     'symbol': 'EUR',
     'numeric': 978},
    {'name': u'Bolivar Fuerte ',
     'symbol': 'VEF',
     'numeric': 937},
    {'name': u'Dong',
     'symbol': 'VND',
     'numeric': 704},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'US Dollar',
     'symbol': 'USD',
     'numeric': 840},
    {'name': u'CFP Franc',
     'symbol': 'XPF',
     'numeric': 953},
    {'name': u'Moroccan Dirham',
     'symbol': 'MAD',
     'numeric': 504},
    {'name': u'Yemeni Rial',
     'symbol': 'YER',
     'numeric': 886},
    {'name': u'Zambian Kwacha',
     'symbol': 'ZMK',
     'numeric': 894},
    {'name': u'Zimbabwe Dollar   ',
     'symbol': 'ZWL',
     'numeric': 932},
    {'name': u'Bond Markets Unit European Composite Unit (EURCO)',
     'symbol': 'XBA',
     'numeric': 955},
    {'name': u'Bond Markets Unit European Monetary Unit (E.M.U.-6) ',
     'symbol': 'XBB',
     'numeric': 956},
    {'name': u'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
     'symbol': 'XBC',
     'numeric': 957},
    {'name': u'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
     'symbol': 'XBD',
     'numeric': 958},
    {'Name': U'UIC-Franc',
     'symbol': 'XFU',
     'Numeric': None},
    {'name': u'Symbols specifically reserved for testing purposes',
     'symbol': 'XTS',
     'numeric': 963},
    {'name': (u'The symbols assigned for transactions where no currency '
              u'is involved'),
     'symbol': 'XXX',
     'numeric': 999},
    {'name': u'Gold',
     'symbol': 'XAU',
     'numeric': 959},
    {'name': u'Palladium',
     'symbol': 'XPD',
     'numeric': 964},
    {'name': u'Platinum',
     'symbol': 'XPT',
     'numeric': 962},
    {'name': u'Silver',
     'symbol': 'XAG',
     'numeric': 961},
    ]

CURRENCY_SYMBOLS = [currency['symbol'] for currency in CURRENCIES]
